#21244 confluence api
artemeon/confluence pull request #2
Opened 2024-10-15 09:56 UTC by f-kuechler

2024-10-16 07:56 UTC, marcreichel requested changes

2024-10-16 07:56 UTC, marcreichel commented on src/MacroReplacer/LayoutSectionMacroReplacer.php
> +}
```suggestion
}

```

2024-10-17 12:50 UTC, christiankaemper approved these changes

2024-10-17 12:50 UTC, marcreichel approved these changes

2024-10-17 12:51 UTC, merged